# Generated by Django 2.1.4 on 2018-12-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Abreviatura', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Asignar_Horarios_para_Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tiempo_Inicio', models.DateTimeField(blank=True, null=True)),
                ('Tiempo_Fin', models.DateTimeField(blank=True, null=True)),
                ('Imagen', models.ImageField(null=True, upload_to='Imagenes')),
                ('Descripción', models.TextField(null=True)),
                ('Para_Reservar', models.BooleanField(default=True)),
                ('En_Mantenimiento', models.BooleanField(default=True)),
                ('area', models.ForeignKey(null=True, on_delete='do_nothing', to='Gestionar_Areas_Comunes.Area')),
            ],
        ),
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Nro_SubÁrea', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='asignar_horarios_para_reserva',
            name='sub_area',
            field=models.ForeignKey(null=True, on_delete='do_nothing', to='Gestionar_Areas_Comunes.SubArea'),
        ),
    ]
