# Generated by Django 2.1.4 on 2018-12-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Abreviatura', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Asignar_Horarios_para_Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Sector', models.CharField(max_length=50)),
                ('Tiempo_Uso', models.DateTimeField(blank=True, null=True)),
                ('área', models.ForeignKey(on_delete='do_nothing', to='Gestionar_Areas_Comunes.Area')),
            ],
        ),
    ]
