# Generated by Django 2.1.4 on 2018-12-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionar_Areas_Comunes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='Abreviatura',
        ),
        migrations.RemoveField(
            model_name='asignar_horarios_para_reserva',
            name='sub_area',
        ),
        migrations.AddField(
            model_name='area',
            name='sub_area',
            field=models.ForeignKey(default=1, on_delete='do_nothing', to='Gestionar_Areas_Comunes.SubArea'),
            preserve_default=False,
        ),
    ]
