# Generated by Django 2.1.4 on 2018-12-07 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionar_Areas_Comunes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignar_horarios_para_reserva',
            name='Descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='asignar_horarios_para_reserva',
            name='Estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='asignar_horarios_para_reserva',
            name='área',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestionar_Areas_Comunes.Area'),
        ),
    ]
