# Generated by Django 2.1.4 on 2018-12-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionar_Areas_Comunes', '0002_auto_20181213_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignar_horarios_para_reserva',
            name='Descripción',
        ),
    ]
