# Generated by Django 2.1.4 on 2018-12-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionar_Areas_Comunes', '0003_auto_20181207_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignar_horarios_para_reserva',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='Imagenes'),
        ),
    ]
