# Generated by Django 2.1.4 on 2018-12-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nro_Habitacion', models.CharField(max_length=50)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido_Materno', models.CharField(max_length=100)),
                ('Apellido_Paterno', models.CharField(max_length=100)),
            ],
        ),
    ]
