# Generated by Django 2.1.4 on 2018-12-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrar_Visitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='propietario',
            field=models.ForeignKey(on_delete='do_nothing', to='Administrar_Visitas.Propietario'),
        ),
    ]
