# Generated by Django 2.1.4 on 2018-12-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrar_Visitas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_I', models.CharField(max_length=8)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='propietario',
            old_name='Apellido_Materno',
            new_name='Apellido',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='Apellido_Paterno',
        ),
    ]
