# Generated by Django 2.1.4 on 2018-12-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrar_Visitas', '0002_auto_20181212_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hora_Entrada', models.DateTimeField(auto_now=True, null=True)),
                ('Hora_Salida', models.DateTimeField(blank=True, null=True)),
                ('Tipo_Acceso', models.CharField(choices=[('C', 'A_pie'), ('A', 'Automovil')], default='C', max_length=1)),
                ('Descripcion', models.TextField()),
                ('propietario', models.ForeignKey(on_delete='do_nothing', to='Administrar_Visitas.Propietario')),
                ('visitante', models.ForeignKey(on_delete='do_nothing', to='Administrar_Visitas.Visitante')),
            ],
        ),
    ]
